# Generated by Django 4.0.6 on 2023-03-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=200)),
                ('Wages', models.IntegerField(default=0)),
                ('Persons', models.IntegerField(default=0)),
            ],
        ),
    ]
