# Generated by Django 4.1.7 on 2023-03-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobCreation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='Persons',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Description',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='Wages',
            new_name='price',
        ),
        migrations.AddField(
            model_name='jobs',
            name='workers',
            field=models.IntegerField(default='0'),
        ),
    ]
