# Generated by Django 4.1.7 on 2023-03-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobCreation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Persons',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Wages',
            field=models.IntegerField(default='0'),
        ),
    ]
