# Generated by Django 4.1.7 on 2023-03-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobCreation', '0002_rename_persons_jobs_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='des',
            new_name='days',
        ),
    ]
