# Generated by Django 4.1.7 on 2023-03-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('MachineDetails', models.CharField(max_length=200)),
                ('Price', models.IntegerField(default='0')),
                ('Contact', models.IntegerField(default='0')),
            ],
        ),
    ]
