# Generated by Django 4.1.7 on 2023-04-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentMachine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='rentimage',
            field=models.ImageField(blank=True, default='', null=True, upload_to='RentMachine/thumb-img'),
        ),
    ]
