# Generated by Django 4.1.7 on 2023-04-09 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RentMachine', '0002_alter_renting_rentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='renting',
            name='BookedStatus',
            field=models.BooleanField(default=False, verbose_name='BookedStatus'),
        ),
        migrations.AddField(
            model_name='renting',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renting',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', unique=True),
        ),
    ]
