# Generated by Django 4.1.7 on 2023-04-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentMachine', '0003_renting_bookedstatus_renting_date_renting_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renting',
            name='username',
        ),
    ]
