# Generated by Django 4.1.7 on 2023-04-09 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RentMachine', '0005_renting_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renting',
            name='username',
        ),
        migrations.AddField(
            model_name='renting',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
