# Generated by Django 4.1.7 on 2023-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentMachine', '0006_remove_renting_username_renting_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
