# Generated by Django 4.1.7 on 2023-04-17 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RentMachine', '0007_alter_renting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('placed_at', models.DateField(auto_now=True)),
                ('payement_status', models.BooleanField(default=False, verbose_name='payement_status')),
                ('payement_mode', models.CharField(choices=[('COD', 'Cash on Delivery'), ('Online', 'Online Payement')], max_length=30)),
                ('machine_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RentMachine.renting', unique=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
