# Generated by Django 4.1.7 on 2023-04-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentMachine', '0008_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renting',
            name='rentimage',
        ),
    ]
