# Generated by Django 4.1.7 on 2023-04-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RentMachine', '0009_remove_renting_rentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renting',
            name='user_id',
        ),
    ]
