# Generated by Django 4.1.7 on 2023-04-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentMachine', '0010_remove_renting_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='machine_id',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.IntegerField(default='0'),
        ),
    ]
