# Generated by Django 4.1.7 on 2023-05-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentMachine', '0012_renting_rentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('query_img', models.CharField(max_length=1000)),
                ('user_id', models.IntegerField(default='0')),
            ],
        ),
    ]
