# Generated by Django 4.1.7 on 2023-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentMachine', '0014_alter_query_query_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='rentimage',
            field=models.CharField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/bhoomirent-df650.appspot.com/o/rn_image_picker_lib_temp_2512f23f-19ab-4ea7-9a4a-48ae50b9de9c.jpg?alt=media&token=7293eb19-9505-4910-8eb9-ee58d2f14ae5', max_length=1000),
        ),
    ]
