# Generated by Django 4.1.7 on 2023-05-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentMachine', '0015_alter_renting_rentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='end_date',
            field=models.DateField(blank=True, default='2023-06-04'),
        ),
    ]
