# Generated by Django 4.1.7 on 2023-05-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentMachine', '0016_rename_date_orders_start_date_orders_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default='0')),
                ('first_img', models.CharField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/bhoomirent-df650.appspot.com/o/rn_image_picker_lib_temp_2512f23f-19ab-4ea7-9a4a-48ae50b9de9c.jpg?alt=media&token=7293eb19-9505-4910-8eb9-ee58d2f14ae5', max_length=1000)),
                ('second_img', models.CharField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/bhoomirent-df650.appspot.com/o/rn_image_picker_lib_temp_2512f23f-19ab-4ea7-9a4a-48ae50b9de9c.jpg?alt=media&token=7293eb19-9505-4910-8eb9-ee58d2f14ae5', max_length=1000)),
                ('third_img', models.CharField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/bhoomirent-df650.appspot.com/o/rn_image_picker_lib_temp_2512f23f-19ab-4ea7-9a4a-48ae50b9de9c.jpg?alt=media&token=7293eb19-9505-4910-8eb9-ee58d2f14ae5', max_length=1000)),
                ('fourth_img', models.CharField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/bhoomirent-df650.appspot.com/o/rn_image_picker_lib_temp_2512f23f-19ab-4ea7-9a4a-48ae50b9de9c.jpg?alt=media&token=7293eb19-9505-4910-8eb9-ee58d2f14ae5', max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='query',
            old_name='machine_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='query',
            name='query_img',
        ),
        migrations.AddField(
            model_name='query',
            name='email',
            field=models.CharField(default='fdjgk', max_length=80),
        ),
        migrations.AddField(
            model_name='query',
            name='subject',
            field=models.CharField(default='fdjgk', max_length=100),
        ),
        migrations.AlterField(
            model_name='query',
            name='message',
            field=models.CharField(default='fdjgk', max_length=500),
        ),
    ]
